# name: publish-to-docker-package-json-version

# on:
#   push:
#     branches:
#       - main
# env:
#   DOCKER_REPO: facutk/hello-html

# jobs:
#   get-version:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v1

#       - id: get-version
#         uses: tyankatsu0105/read-package-version-actions@v1
#       - id: tags
#         run: echo "::set-output name=tags::$DOCKER_REPO:latest,$DOCKER_REPO:${{ steps.get-version.outputs.version }}"

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1

#       - name: Login to DockerHub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKER_USER }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Build and push
#         uses: docker/build-push-action@v2
#         with:
#           push: true
#           tags: ${{ steps.tags.outputs.tags }}
