name: version-check

on:
  pull_request:
    branches:
      - main

jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: reside-eng/verify-git-tag-version@v1
